# Glimpse Configuration for Z.AI
# Copy this file to .glimpse.yaml in your repository root

# File patterns to watch for changes
watch:
  - "./internal/**/*.go"
  - "./pkg/**/*.go"
  - "*.go"

# File patterns to ignore
ignore:
  - "*_test.go"
  - "*.generated.go"
  - "vendor/**"
  - ".git/**"

# Log file configuration
logs:
  file: "./tmp/server.log"
  lines: 50

# Z.AI LLM configuration
llm:
  provider: "zai"
  model: "glm-4.6"          # GLM-4.6, glm-4-air, glm-4-32b
  
  # API key (optional - can use ZAI_API_KEY environment variable instead)
  # api_key: "your-zai-api-key-here"
  
  # System prompt for code reviews
  system_prompt: "You are a Principal Go Engineer. Review strictly for bugs, performance issues, and security concerns. Be concise and actionable."